version: "3.9"

services:
  dev_ess_portal:
    container_name: dev_ess_portal
    image: 172.16.1.225:5000/ess_portal:${IMAGE_TAG}
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - ./.env
    ports:
      - "9004:80"
    networks:
      - common-services-dev-net
    volumes:
      - ${STORAGE_PATH}:/var/www/html/storage
      # - ./vendor:/var/www/html/vendor
    restart: always

networks:
  common-services-dev-net:
    external: true
